import type { DataSystem, DispatchBatch, PrivacyRequest, WorkspaceState } from '@/types/domain'
import { addDays, buildWorkflowSteps } from './workflow'

const systems: DataSystem[] = [
  {
    id: 'sys-crm',
    name: '客户关系管理系统',
    owner: '客户平台组',
    dataDomain: '客户身份、联系信息、服务记录',
    transferMethod: '受控接口导出',
    slaDays: 5,
    requestTypes: ['access', 'rectification', 'deletion', 'restriction'],
    status: 'active',
  },
  {
    id: 'sys-order',
    name: '订单与交易平台',
    owner: '交易系统组',
    dataDomain: '订单、支付标识、收货信息',
    transferMethod: '离线加密包',
    slaDays: 7,
    requestTypes: ['access', 'deletion'],
    status: 'active',
  },
  {
    id: 'sys-marketing',
    name: '营销自动化平台',
    owner: '增长技术组',
    dataDomain: '同意记录、标签、触达历史',
    transferMethod: '消息队列同步',
    slaDays: 3,
    requestTypes: ['access', 'deletion', 'withdraw-consent', 'restriction'],
    status: 'active',
  },
  {
    id: 'sys-archive',
    name: '电子档案库',
    owner: '档案管理组',
    dataDomain: '合同、凭证、历史记录',
    transferMethod: '双人复核导出',
    slaDays: 10,
    requestTypes: ['access', 'rectification', 'restriction'],
    status: 'maintenance',
  },
  {
    id: 'sys-support',
    name: '客服工单系统',
    owner: '服务运营组',
    dataDomain: '沟通记录、身份核验材料、附件',
    transferMethod: '脱敏下载',
    slaDays: 5,
    requestTypes: ['access', 'rectification', 'deletion', 'restriction'],
    status: 'active',
  },
  {
    id: 'sys-risk',
    name: '风控决策平台',
    owner: '风险技术组',
    dataDomain: '设备指纹、风险标签、决策结果',
    transferMethod: '隔离区核验',
    slaDays: 8,
    requestTypes: ['access', 'rectification', 'restriction'],
    status: 'active',
  },
]

function audit(
  id: string,
  action: string,
  operator: string,
  detail: string,
  createdAt: string,
) {
  return { id, action, operator, detail, createdAt }
}

/** DSR-2026-006 限制处理生效后，同主体清除/更正系统任务统一的暂缓依据。 */
const restrictionHold = {
  restrictionRequestId: 'req-006',
  restrictionCode: 'DSR-2026-006',
  heldAt: '2026-09-30T03:20:00.000Z',
  reason: '依据限制处理请求 DSR-2026-006 暂缓，未下发数据系统。',
}

export function createInitialState(): WorkspaceState {
  const request1At = '2026-09-25T02:30:00.000Z'
  const request2At = '2026-09-18T06:20:00.000Z'
  const request3At = '2026-09-21T03:10:00.000Z'
  const request4At = '2026-09-24T05:40:00.000Z'
  const request5At = '2026-09-05T01:00:00.000Z'
  const request1Due = addDays(new Date(request1At), 30).toISOString()
  const request2Due = addDays(new Date(request2At), 30).toISOString()
  const request3Due = addDays(new Date(request3At), 45).toISOString()
  const request4Due = addDays(new Date(request4At), 30).toISOString()
  const request5Due = addDays(new Date(request5At), 30).toISOString()

  const requests: PrivacyRequest[] = [
    {
      id: 'req-001',
      code: 'DSR-2026-001',
      requesterName: '张晨',
      requesterContact: 'zh***@example.com',
      region: 'cn',
      type: 'access',
      status: 'processing',
      identity: {
        status: 'verified',
        materialType: 'masked-id',
        maskedReference: '310***********1234',
        protectedDigest: 'ID-74A1B2',
        note: '证件影像已核验，原始文件未进入业务库。',
        reviewedAt: '2026-09-25T04:10:00.000Z',
      },
      requestedAt: request1At,
      dueAt: request1Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-order', 'sys-support'],
      tasks: buildWorkflowSteps({
        requestId: 'req-001',
        type: 'access',
        systemIds: ['sys-crm', 'sys-order', 'sys-support'],
        requestedAt: request1At,
        dueAt: request1Due,
        initialStatus: 'processing',
        systems,
      }),
      evidence: [
        {
          id: 'evidence-001-a',
          stepId: 'req-001-identity',
          name: '身份核验记录',
          evidenceType: 'signed-record',
          digest: '9A11-77D2',
          uploadedBy: '当前客服',
          uploadedAt: '2026-09-25T04:10:00.000Z',
          protected: true,
        },
      ],
      conflicts: [],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-001',
          '登记请求',
          '客服专员',
          '访问请求已登记，并生成 30 日流程。',
          request1At,
        ),
      ],
    },
    {
      id: 'req-002',
      code: 'DSR-2026-002',
      requesterName: '王宁',
      requesterContact: 'wa***@example.com',
      region: 'eu',
      type: 'deletion',
      status: 'review-required',
      identity: {
        status: 'insufficient',
        materialType: 'authorization-letter',
        maskedReference: '授权书仅含截图',
        protectedDigest: 'AUTH-11E9',
        note: '缺少委托关系证明，需进入身份材料复核。',
      },
      requestedAt: request2At,
      dueAt: request2Due,
      extendedDays: 0,
      duplicateOf: 'req-005',
      affectedSystemIds: ['sys-crm', 'sys-marketing', 'sys-support'],
      tasks: buildWorkflowSteps({
        requestId: 'req-002',
        type: 'deletion',
        systemIds: ['sys-crm', 'sys-marketing', 'sys-support'],
        requestedAt: request2At,
        dueAt: request2Due,
        initialStatus: 'review-required',
        systems,
      }).map((step) =>
        step.systemId ? { ...step, status: 'held' as const, hold: { ...restrictionHold } } : step,
      ),
      evidence: [],
      conflicts: [
        '身份材料不足：授权书无法证明申请人与数据主体关系。',
        '疑似重复请求：与 DSR-2026-005 的请求人和处理类型相同。',
      ],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-002',
          '转入复核队列',
          '隐私运营',
          '身份材料不足且检测到疑似重复请求。',
          '2026-09-19T02:00:00.000Z',
        ),
        audit(
          'req-audit-002-b',
          '任务暂缓下发',
          '系统调度',
          '同主体限制处理请求 DSR-2026-006 生效，删除系统任务停在待复核，未下发数据系统。',
          '2026-09-30T03:20:00.000Z',
        ),
      ],
    },
    {
      id: 'req-003',
      code: 'DSR-2026-003',
      requesterName: '刘晓',
      requesterContact: 'li***@example.com',
      region: 'us',
      type: 'rectification',
      status: 'review-required',
      identity: {
        status: 'verified',
        materialType: 'account-ownership',
        maskedReference: '账号所有权验证通过',
        protectedDigest: 'ACC-559A',
        note: '依据登录挑战与近期交易完成核验。',
        reviewedAt: '2026-09-21T05:30:00.000Z',
      },
      requestedAt: request3At,
      dueAt: request3Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-risk', 'sys-support'],
      tasks: buildWorkflowSteps({
        requestId: 'req-003',
        type: 'rectification',
        systemIds: ['sys-crm', 'sys-risk', 'sys-support'],
        requestedAt: request3At,
        dueAt: request3Due,
        initialStatus: 'processing',
        systems,
      }).map((step, index) => (index === 1 ? { ...step, status: 'blocked', exceptionReason: '风控平台返回值与客服系统不一致。' } : step)),
      evidence: [],
      conflicts: ['跨系统结果冲突：客户系统中的姓名已更正，但风控平台仍保留旧值。'],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-003',
          '发现跨系统冲突',
          '数据管理员',
          '风控平台拒绝更新风险标签关联姓名。',
          '2026-09-28T08:30:00.000Z',
        ),
      ],
    },
    {
      id: 'req-004',
      code: 'DSR-2026-004',
      requesterName: '陈妙',
      requesterContact: 'ch***@example.com',
      region: 'sg',
      type: 'withdraw-consent',
      status: 'pending-close',
      identity: {
        status: 'verified',
        materialType: 'account-ownership',
        maskedReference: '账号所有权验证通过',
        protectedDigest: 'ACC-880D',
        note: '账号双因素验证通过。',
        reviewedAt: '2026-09-24T07:00:00.000Z',
      },
      requestedAt: request4At,
      dueAt: request4Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-marketing'],
      tasks: buildWorkflowSteps({
        requestId: 'req-004',
        type: 'withdraw-consent',
        systemIds: ['sys-marketing'],
        requestedAt: request4At,
        dueAt: request4Due,
        initialStatus: 'pending-close',
        systems,
      }),
      evidence: [
        {
          id: 'evidence-004-a',
          stepId: 'req-004-execute-sys-marketing',
          name: '同意状态变更日志',
          evidenceType: 'execution-log',
          digest: 'E31A-880D',
          uploadedBy: '增长技术组',
          uploadedAt: '2026-09-28T09:00:00.000Z',
          protected: true,
        },
      ],
      conflicts: [],
      resultSummary: '营销平台已撤回同意并停止后续自动化触达。',
      closureReason: '',
      audit: [
        audit(
          'req-audit-004',
          '待关闭复核',
          '隐私运营',
          '全部系统任务已完成，等待负责人确认结果。',
          '2026-09-28T09:10:00.000Z',
        ),
      ],
    },
    {
      id: 'req-005',
      code: 'DSR-2026-005',
      requesterName: '王宁',
      requesterContact: 'wa***@example.com',
      region: 'eu',
      type: 'deletion',
      status: 'completed',
      identity: {
        status: 'verified',
        materialType: 'masked-id',
        maskedReference: '310***********8832',
        protectedDigest: 'ID-771B',
        note: '身份核验已完成。',
        reviewedAt: '2026-09-05T03:30:00.000Z',
      },
      requestedAt: request5At,
      dueAt: request5Due,
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-marketing'],
      tasks: buildWorkflowSteps({
        requestId: 'req-005',
        type: 'deletion',
        systemIds: ['sys-crm', 'sys-marketing'],
        requestedAt: request5At,
        dueAt: request5Due,
        initialStatus: 'completed',
        systems,
      }),
      evidence: [
        {
          id: 'evidence-005-a',
          stepId: 'req-005-execute-sys-crm',
          name: '删除执行回执',
          evidenceType: 'system-response',
          digest: 'E5A0-1201',
          uploadedBy: '客户平台组',
          uploadedAt: '2026-09-08T05:00:00.000Z',
          protected: true,
        },
      ],
      conflicts: [],
      resultSummary: '已完成请求主体在两个系统中的删除，并保留最小合规凭证。',
      closureReason: '期限已到且任务完整，经复核后关闭。',
      audit: [
        audit(
          'req-audit-005',
          '完成请求',
          '隐私负责人',
          '处理结果合并完成并生成操作审计。',
          '2026-09-10T02:00:00.000Z',
        ),
      ],
    },
    {
      id: 'req-006',
      code: 'DSR-2026-006',
      requesterName: '王宁',
      requesterContact: 'wa***@example.com',
      region: 'eu',
      type: 'restriction',
      status: 'processing',
      identity: {
        status: 'verified',
        materialType: 'masked-id',
        maskedReference: '310***********8832',
        protectedDigest: 'ID-771B',
        note: '与 DSR-2026-005 同一主体，身份核验沿用受保护摘要。',
        reviewedAt: '2026-09-30T03:10:00.000Z',
      },
      requestedAt: '2026-09-29T09:00:00.000Z',
      dueAt: '2026-10-29T09:00:00.000Z',
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-marketing'],
      tasks: buildWorkflowSteps({
        requestId: 'req-006',
        type: 'restriction',
        systemIds: ['sys-crm', 'sys-marketing'],
        requestedAt: '2026-09-29T09:00:00.000Z',
        dueAt: '2026-10-29T09:00:00.000Z',
        initialStatus: 'processing',
        systems,
      }),
      evidence: [],
      conflicts: [],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-006-a',
          '登记请求',
          '客服专员',
          '限制处理请求已登记，生成 30 日流程。',
          '2026-09-29T09:00:00.000Z',
        ),
        audit(
          'req-audit-006-b',
          '身份核验通过',
          '隐私运营',
          '身份材料核验通过，限制处理生效。',
          '2026-09-30T03:10:00.000Z',
        ),
        audit(
          'req-audit-006-c',
          '限制处理生效',
          '系统调度',
          '同主体清除与更正系统任务暂缓下发，等待限制解除或到期。',
          '2026-09-30T03:20:00.000Z',
        ),
      ],
    },
    {
      id: 'req-007',
      code: 'DSR-2026-007',
      requesterName: '王宁',
      requesterContact: 'wa***@example.com',
      region: 'eu',
      type: 'rectification',
      status: 'processing',
      identity: {
        status: 'verified',
        materialType: 'masked-id',
        maskedReference: '310***********8832',
        protectedDigest: 'ID-771B',
        note: '身份核验已完成。',
        reviewedAt: '2026-09-26T07:00:00.000Z',
      },
      requestedAt: '2026-09-26T06:00:00.000Z',
      dueAt: '2026-10-26T06:00:00.000Z',
      extendedDays: 0,
      affectedSystemIds: ['sys-crm', 'sys-archive'],
      tasks: buildWorkflowSteps({
        requestId: 'req-007',
        type: 'rectification',
        systemIds: ['sys-crm', 'sys-archive'],
        requestedAt: '2026-09-26T06:00:00.000Z',
        dueAt: '2026-10-26T06:00:00.000Z',
        initialStatus: 'processing',
        systems,
      }).map((step) => {
        if (step.id === 'req-007-locate-sys-crm') {
          return { ...step, status: 'completed' as const, completedAt: '2026-09-27T02:00:00.000Z' }
        }
        if (step.id === 'req-007-execute-sys-crm') {
          return { ...step, status: 'completed' as const, completedAt: '2026-09-28T02:30:00.000Z' }
        }
        if (step.id === 'req-007-locate-sys-archive' || step.id === 'req-007-execute-sys-archive') {
          return { ...step, status: 'held' as const, hold: { ...restrictionHold } }
        }
        return step
      }),
      evidence: [
        {
          id: 'evidence-007-a',
          stepId: 'req-007-execute-sys-crm',
          name: '更正执行回执',
          evidenceType: 'system-response',
          digest: 'C72B-90E4',
          uploadedBy: '客户平台组',
          uploadedAt: '2026-09-28T02:35:00.000Z',
          protected: true,
        },
      ],
      conflicts: [],
      resultSummary: '',
      closureReason: '',
      audit: [
        audit(
          'req-audit-007-a',
          '登记请求',
          '客服专员',
          '更正请求已登记，生成 30 日流程。',
          '2026-09-26T06:00:00.000Z',
        ),
        audit(
          'req-audit-007-b',
          '任务暂缓下发',
          '系统调度',
          '电子档案库相关任务依据限制处理请求 DSR-2026-006 停在待复核，未下发数据系统。',
          '2026-09-30T03:20:00.000Z',
        ),
      ],
    },
  ]

  const batches: DispatchBatch[] = [
    {
      id: 'batch-001',
      label: 'BATCH-2026-001',
      createdAt: '2026-09-27T01:00:00.000Z',
      status: 'checkpointed',
      checkpointNote:
        '电子档案库维护中，接口暂停下发；已保留检查点，重试仅补未送达项，已成功回执不重发。',
      checkpointAt: '2026-09-29T08:10:00.000Z',
      items: [
        {
          id: 'dispatch-001',
          requestId: 'req-007',
          requestCode: 'DSR-2026-007',
          taskId: 'req-007-locate-sys-crm',
          taskName: '定位 客户关系管理系统 数据',
          systemId: 'sys-crm',
          systemName: '客户关系管理系统',
          status: 'acknowledged',
          attempts: 1,
          registeredAt: '2026-09-27T01:00:00.000Z',
          deliveredAt: '2026-09-27T01:05:00.000Z',
          acknowledgedAt: '2026-09-27T02:00:00.000Z',
          failureReason: '',
        },
        {
          id: 'dispatch-002',
          requestId: 'req-007',
          requestCode: 'DSR-2026-007',
          taskId: 'req-007-execute-sys-crm',
          taskName: '执行更正：客户关系管理系统',
          systemId: 'sys-crm',
          systemName: '客户关系管理系统',
          status: 'acknowledged',
          attempts: 1,
          registeredAt: '2026-09-28T01:30:00.000Z',
          deliveredAt: '2026-09-28T01:35:00.000Z',
          acknowledgedAt: '2026-09-28T02:30:00.000Z',
          failureReason: '',
        },
        {
          id: 'dispatch-003',
          requestId: 'req-007',
          requestCode: 'DSR-2026-007',
          taskId: 'req-007-locate-sys-archive',
          taskName: '定位 电子档案库 数据',
          systemId: 'sys-archive',
          systemName: '电子档案库',
          status: 'failed',
          attempts: 1,
          registeredAt: '2026-09-29T08:00:00.000Z',
          failureReason: '电子档案库维护中，接口暂停下发',
        },
        {
          id: 'dispatch-004',
          requestId: 'req-007',
          requestCode: 'DSR-2026-007',
          taskId: 'req-007-execute-sys-archive',
          taskName: '执行更正：电子档案库',
          systemId: 'sys-archive',
          systemName: '电子档案库',
          status: 'queued',
          attempts: 0,
          registeredAt: '2026-09-29T08:00:00.000Z',
          failureReason: '',
        },
      ],
    },
  ]

  return {
    requests,
    systems,
    batches,
    comments: [
      {
        id: 'comment-001',
        requestId: 'req-003',
        author: '风控平台管理员',
        content: '风险标签属于反欺诈例外审查范围，不能直接按普通资料更正。',
        createdAt: '2026-09-28T08:35:00.000Z',
      },
      {
        id: 'comment-002',
        requestId: 'req-002',
        author: '隐私运营',
        content: '请先确认该请求与 DSR-2026-005 是否属于重复申请。',
        createdAt: '2026-09-19T02:05:00.000Z',
      },
    ],
    audit: [
      {
        id: 'audit-global-1',
        requestId: 'req-001',
        action: '登记请求',
        operator: '客服专员',
        detail: '访问请求进入 30 日履约流程。',
        createdAt: request1At,
      },
      {
        id: 'audit-global-2',
        requestId: 'req-002',
        action: '身份材料复核',
        operator: '隐私运营',
        detail: '身份材料不足并检测到疑似重复请求。',
        createdAt: '2026-09-19T02:00:00.000Z',
      },
      {
        id: 'audit-global-3',
        requestId: 'req-003',
        action: '跨系统结果冲突',
        operator: '数据管理员',
        detail: '风控平台与客户系统结果不一致，进入复核队列。',
        createdAt: '2026-09-28T08:30:00.000Z',
      },
      {
        id: 'audit-global-4',
        action: '对账批次保留检查点',
        operator: '系统调度',
        detail: 'BATCH-2026-001 在电子档案库遇到系统维护，已保留检查点；重试仅补未送达项，已成功回执不重发。',
        createdAt: '2026-09-29T08:10:00.000Z',
      },
      {
        id: 'audit-global-5',
        requestId: 'req-006',
        action: '限制处理生效',
        operator: '系统调度',
        detail: '同主体（王宁）的清除与更正系统任务暂缓下发，等待限制解除或到期。',
        createdAt: '2026-09-30T03:20:00.000Z',
      },
    ],
    revision: 1,
  }
}

export const requestTypeOptions = [
  { value: 'access', label: '访问' },
  { value: 'rectification', label: '更正' },
  { value: 'deletion', label: '删除' },
  { value: 'withdraw-consent', label: '撤回同意' },
  { value: 'restriction', label: '限制处理' },
] as const
